title: Santiana
email: your-email@example.com
description: >- # this means to ignore newlines until the next tag
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hps-ucsd
github_username:  hps-ucsd-2020

homepage: "/Home.html"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: hps-ucsd-2020/jekyll-theme-santiana@main

# Github required settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - lightslider/README.md

defaults:
-
  scope:
    path: "wiki"
  values:
    layout: "wikipage"
