title: Santiana
email: your-email@example.com
description: >- # this means to ignore newlines until the next tag
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hps-ucsd
github_username:  hps-ucsd-2020

homepage: "/Home.html"
git_branch: "main"
wiki_folder: "wiki"

# Build settings
plugins:
  - jekyll-feed
# - jekyll-remote-theme
  - jekyll-optional-front-matter
# remote_theme: hps-ucsd-2020/jekyll-theme-santiana@main

# Github required settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - lightslider/README.md

optional_front_matter:
  remove_originals: true

defaults:
-
  scope:
    path: "wiki"
  values:
    output: true
    layout: "wikipage"
    permalink: /wiki/:basename
